name = "SimpleHypergraphs"
uuid = "aa4a32ff-dd5d-5357-90e3-e7a9512f0501"
authors = ["Bogumił Kamiński <bkamins@sgh.waw.pl>", "Przemysław Szufel <pszufe@sgh.waw.pl>"]
version = "0.1.3"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
